// src/features/organization/components/branches/BranchModal.tsx
import React, { useState, useEffect } from 'react';
import { Store } from 'lucide-react';
import axios from 'axios';
import { ComerziaModal } from '../../../../components/ui/ComerziaModal';
import { ComerziaInput } from '../../../../components/ui/ComerziaInput';
import { ComerziaSwitch } from '../../../../components/ui/ComerziaSwitch';
import { BtnCancel, BtnSave } from '../../../../components/ui/CrudButtons';
import { SubscriptionLimitModal } from '../../../../components/ui/SubscriptionLimitModal';
import { branchService } from '../../services/branchService';
import { useToast } from '../../../../context/ToastContext';
import { generateSku } from '../../../../utils/skuGenerator';
import type { BranchResponse, CreateBranchRequest, UpdateBranchRequest } from '../../types/branch';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  branchToEdit: BranchResponse | null;
  onSuccess: () => void;
}

export const BranchModal = ({ isOpen, onClose, branchToEdit, onSuccess }: Props) => {
  const { addToast: showToast } = useToast();

  const [isSaving, setIsSaving] = useState(false);
  const [shakeKey, setShakeKey] = useState(0);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Guardar sugerencia generada para saber si el usuario la modificó manualmente
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');

  // Mensaje de límite de suscripción del backend
  const [backendLimitError, setBackendLimitError] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    name: '',
    code: '',
    address: '',
    status: 'true'
  });

  const isEditing = !!branchToEdit;

  useEffect(() => {
    if (isOpen) {
      if (branchToEdit) {
        setFormData({
          name: branchToEdit.name,
          code: branchToEdit.code || '',
          address: branchToEdit.address || '',
          status: branchToEdit.status ? 'true' : 'false'
        });
        setAutoGeneratedCode('');
      } else {
        setFormData({ name: '', code: '', address: '', status: 'true' });
        setAutoGeneratedCode('');
      }
      setErrors({});
      setBackendLimitError(null);
    }
  }, [isOpen, branchToEdit]);

  // Manejar cambio en el nombre y generar sugerencia automática para el código
  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newName = e.target.value;
    const suggestedCode = generateSku(newName);

    setFormData(prev => {
      // Si el código está vacío o coincide con la sugerencia anterior, se actualiza automáticamente
      const shouldUpdateCode = !isEditing && (!prev.code || prev.code === autoGeneratedCode);
      return {
        ...prev,
        name: newName,
        code: shouldUpdateCode ? suggestedCode : prev.code
      };
    });

    if (!isEditing) {
      setAutoGeneratedCode(suggestedCode);
    }

    if (errors.name) {
      setErrors(prev => ({ ...prev, name: '' }));
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));

    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    if (!formData.name.trim()) {
      newErrors.name = 'El nombre de la sucursal es obligatorio';
    }

    if (!isEditing && !formData.code.trim()) {
      newErrors.code = 'El código de la sucursal es obligatorio';
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      setShakeKey(prev => prev + 1);
      return false;
    }
    return true;
  };

  const handleSave = async () => {
    if (!validateForm()) return;

    try {
      setIsSaving(true);

      if (isEditing) {
        const payload: UpdateBranchRequest = {
          name: formData.name,
          address: formData.address,
          status: formData.status === 'true'
        };
        await branchService.updateBranch(branchToEdit.id, payload);
        showToast('Sucursal actualizada exitosamente', 'success');
      } else {
        const payload: CreateBranchRequest = {
          name: formData.name,
          code: formData.code.trim().toUpperCase(),
          address: formData.address
        };
        await branchService.createBranch(payload);
        showToast('Sucursal creada exitosamente', 'success');
      }

      onSuccess();
      onClose();
    } catch (error) {
      console.error('Error saving branch:', error);

      if (axios.isAxiosError(error) && error.response?.data?.code === 'business_rule_violation') {
        setBackendLimitError(error.response.data.message);
      } else {
        showToast('Error al guardar la sucursal', 'error');
      }
    } finally {
      setIsSaving(false);
    }
  };

  const modalActions = (
    <>
      <BtnCancel onClick={onClose} disabled={isSaving} />
      <BtnSave onClick={handleSave} isLoading={isSaving} />
    </>
  );

  return (
    <>
      {/* MODAL PRINCIPAL: Formulario */}
      <ComerziaModal
        isOpen={isOpen}
        onClose={onClose}
        title={
          <div className="flex items-center gap-2 text-primary">
            <Store size={22} />
            {isEditing ? 'Editar Sucursal' : 'Nueva Sucursal'}
          </div>
        }
        actions={modalActions}
        size="md"
      >
        <div className="space-y-4 pt-2">
          <ComerziaInput
            label="Nombre de la Sucursal"
            name="name"
            placeholder="Ej. Tienda Central, Sucursal Norte"
            value={formData.name}
            onChange={handleNameChange}
            error={errors.name}
            shakeKey={shakeKey}
            isRequired
            maxLength={100}
          />

          <ComerziaInput
            label="Código"
            name="code"
            placeholder="Ej. TIE-CEN"
            value={formData.code}
            onChange={handleChange}
            error={errors.code}
            shakeKey={shakeKey}
            isRequired={!isEditing}
            uppercase
            maxLength={20}
            disabled={isEditing}
            helperText={
              !isEditing ? (
                <span className="text-warning text-[11px] leading-tight block whitespace-normal break-words mt-0.5">
                  <strong className="font-semibold">Nota:</strong> El código es un identificador único y no se podrá modificar después de crearse.
                </span>
              ) : (
                <span className="text-[11px] leading-tight block whitespace-normal break-words text-base-content/60 mt-0.5">
                  El código de la sucursal no se puede modificar.
                </span>
              )
            }
          />

          <ComerziaInput
            label="Dirección (Opcional)"
            name="address"
            placeholder="Av. Principal 123..."
            value={formData.address}
            onChange={handleChange}
            maxLength={200}
          />

          {/* ESTADO DE LA SUCURSAL CON COMERZIASWITCH */}
          {isEditing && (
            <div className="flex items-center justify-between p-3.5 bg-base-200/50 rounded-xl border border-base-200 mt-3">
              <div className="space-y-0.5">
                <span className="text-sm font-semibold text-base-content block">
                  Estado de la Sucursal
                </span>
                <span className="text-xs text-base-content/60">
                  {formData.status === 'true' ? 'Sucursal Activa (Habilitada)' : 'Sucursal Inactiva (Deshabilitada)'}
                </span>
              </div>
              <ComerziaSwitch
                checked={formData.status === 'true'}
                onChange={() =>
                  setFormData(prev => ({
                    ...prev,
                    status: prev.status === 'true' ? 'false' : 'true'
                  }))
                }
              />
            </div>
          )}
        </div>
      </ComerziaModal>

      {/* COMPONENTE GLOBAL DE LÍMITES */}
      <SubscriptionLimitModal
        isOpen={!!backendLimitError}
        onClose={() => setBackendLimitError(null)}
        backendMessage={backendLimitError || ''}
      />
    </>
  );
};